'use strict';
function ajax() {
    var content = '';
    content = addLine(content, '1. AJAX stands for Asynchronous Javascript And XML.', 0, true);
    content = addLine(content, '2. AJAX uses XMLHttpRequest built-in object.', 0, true);
    content = addLine(content, '3. AJAX can use XML, json or plain text to transport data.', 0, true);
    content = addLine(content, '4. XMLHttpRequest (XHR) object:', 0, true);
    var request = new XMLHttpRequest();
    request.open('GET', 'ajax/response.txt', false);
    request.setRequestHeader('accept', 'text/plain');
    request.send();
    content = addLine(content, 'var request = new XMLHttpRequest()', 1);
    content = addLine(content, 'request.open(\'GET\', \'ajax/response.txt\', false)', 1);
    content = addLine(content, 'request.setRequestHeader(\'accept\', \'text/plain\')', 1);
    content = addLine(content, 'request.send()', 1);
    content = addLine(content, 'request.readyState is ' + request.readyState, 1);
    content = addLine(content, 'request.responseText is ' + request.responseText, 1);
    content = addLine(content, 'request.responseXML is ' + request.responseXML, 1);
    content = addLine(content, 'request.status is ' + request.status, 1);
    content = addLine(content, 'request.statusText is ' + request.statusText, 1);
    content = addLine(content, 'request.getAllResponseHeaders() type is ' + (typeof request.getAllResponseHeaders()), 1);
    content = addLine(content, 'request.getResponseHeader(\'content-type\') is ' + request.getResponseHeader('content-type'), 1);
    content = addLine(content, '5. Access across domains is not allowed.', 0, true);
    content = addLine(content, '6. XHR methods:', 0, true);
    content = addLine(content, '* GET (simpler, faster, used in most cases)', 1);
    content = addLine(content, '  request.open(\'GET\', \'path/test.txt\', true)', 1);
    content = addLine(content, '  request.send()', 1);
    content = addLine(content, '* POST (secure, no size limitations)', 1);
    content = addLine(content, '  request.open(\'POST\', \'path/post\', true)', 1);
    content = addLine(content, '  request.send()', 1);
    content = addLine(content, '7. XHR modes:', 0, true);
    content = addLine(content, '* Asynchronous (recommended, onreadystatechange function must be set', 1);
    content = addLine(content, '  request.open(\'GET\', \'path/test.txt\', true)', 1);
    content = addLine(content, '* Synchronous (not recommended, the code should be placed after send()', 1);
    content = addLine(content, '  request.open(\'GET\', \'path/test.txt\', false)', 1);
    content = addLine(content, '8. Function onreadystatechange:', 0, true);
    content = addLine(content, 'request.onreadystatechange = function() {', 1);
    content = addLine(content, '    if(this.readyState = 4 && this.status = 200) {', 1);
    content = addLine(content, '        document.getElementById("sandbox").innerHTML = this.responseText;', 1);
    content = addLine(content, '    }', 1);
    content = addLine(content, '}', 1);
    content = addLine(content, 'request.open(\'GET\', \'test.txt\', true)', 1);
    content = addLine(content, 'request.send()', 1);
    return content;
}
